name: Mac OS CI

on:
  pull_request:
    paths-ignore:
      - '**/src/main/resources/GeoServerApplication_*.properties'
      - '!**/src/main/resources/GeoServerApplication_fr.properties'

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'temurin'
    - name: Maven repository caching
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: gs-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          gs-${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B clean install -U -T2 -Prelease -Pmacos-github-build -Dspotless.apply.skip=true --file src/pom.xml
    - name: Remove SNAPSHOT jars from repository
      run: |
        find .m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
